//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_64130005.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.DonHangs = new HashSet<DonHang>();
        }

        public string MatKhauCu { get; set; }

        public string MaKH { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập Họ")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Vui lòng nhập họ thật")]
        public string HoKH { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập Tên")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Vui lòng nhập tên thật")]
        public string TenKH { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập Email")]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}")]
        public string Emai { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập Mật khẩu")]
        /*[RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,15}$", ErrorMessage = "Mật khẩu tối thiểu 8 kí tự, bao gồm 1 in hoa, 1 số và 1 ký tự đặc biệt")]*/
        public string MatKhau { get; set; }
        [NotMapped]
        [Required(ErrorMessage = "Vui lòng nhập Nhập lại mật khẩu")]
        [System.ComponentModel.DataAnnotations.Compare("MatKhau", ErrorMessage = "Mật khẩu không trùng khớp")]
        public string ConfirmPassword { get; set; }
        public string AnhKH { get; set; }
        public string DiaChi { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{mm/dd/yyyy}")]
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string CCCD { get; set; }
        public string SDT { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }

        public string FullName()
        {
            return this.HoKH + " " + this.TenKH;
        }

        public partial class ChangePassword
        {
            public int maKH { get; set; }

            public string MatKhauCu { get; set; }

            [Required(ErrorMessage = "Vui lòng nhập Mật khẩu")]
            [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,15}$", ErrorMessage = "Mật khẩu tối thiêu 8 kí tự, bao gồm 1 in hoa, 1 số và 1 ký tự đặc biệt")]
            public string MatKhau { get; set; }

            [NotMapped]
            [Required(ErrorMessage = "Vui lòng nhập nhập lại mật khẩu")]
            [System.ComponentModel.DataAnnotations.Compare("Password", ErrorMessage = "Mật khẩu không trùng khớp")]
            public string ConfirmPassword { get; set; }
        }
    }
}