//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_64130005.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.ChiTietDHs = new HashSet<ChiTietDH>();
        }
    
        public string MaSach { get; set; }
        public string MaTheLoai { get; set; }
        public string AnhSach { get; set; }
        public string TenSach { get; set; }
        public Nullable<int> GiamGia { get; set; }
        public Nullable<int> DonGia { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> DaBan { get; set; }
        public Nullable<System.DateTime> NgayThem { get; set; }
        public string MaNgonNgu { get; set; }
        public string MaNXB { get; set; }
        public Nullable<int> MaTG { get; set; }
        public Nullable<System.DateTime> NgayChinhSua { get; set; }
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDH> ChiTietDHs { get; set; }
        public virtual NgonNgu NgonNgu { get; set; }
        public virtual NhaXuatBan NhaXuatBan { get; set; }
        public virtual TacGia TacGia { get; set; }
        public virtual TheLoai TheLoai { get; set; }
    }
}
